from typing import Dict, Any

SENSOR_CANONICAL_NAMES: Dict[str, str] = {
    "moisture": "soil_moisture",
    "soil_moist": "soil_moisture",
    "soil_moisture": "soil_moisture",
    "soil_temp": "soil_temperature",
    "soil_temperature": "soil_temperature",
    "temp": "air_temperature",
    "temperature": "air_temperature",
    "air_temp": "air_temperature",
    "air_temperature": "air_temperature",
    "humidity": "humidity",
    "air_humidity": "humidity",
    "rh": "humidity",
    "light": "solar_radiation",
    "solar": "solar_radiation",
    "solar_radiation": "solar_radiation",
    "lux": "solar_radiation",
    "rain": "rainfall",
    "rainfall": "rainfall",
    "water_level": "water_level",
    "tank_level": "water_level",
    "ph": "soil_ph",
    "soil_ph": "soil_ph",
    "ec": "soil_ec",
    "soil_ec": "soil_ec",
    "nitrogen": "nitrogen",
    "n": "nitrogen",
}

DEFAULT_SENSOR_PROPERTIES: Dict[str, Dict[str, Any]] = {
    "soil_moisture": {
        "canonical_name": "soil_moisture",
        "label": "Soil Moisture",
        "unit": "%",
        "physical_min": 0.0,
        "physical_max": 100.0,
        "default_min": 25.0,
        "default_max": 85.0,
        "optimal_min": 50.0,
        "optimal_max": 70.0,
    },
    "soil_temperature": {
        "canonical_name": "soil_temperature",
        "label": "Soil Temperature",
        "unit": "°C",
        "physical_min": -10.0,
        "physical_max": 60.0,
        "default_min": 10.0,
        "default_max": 35.0,
        "optimal_min": 18.0,
        "optimal_max": 26.0,
    },
    "air_temperature": {
        "canonical_name": "air_temperature",
        "label": "Air Temperature",
        "unit": "°C",
        "physical_min": -20.0,
        "physical_max": 60.0,
        "default_min": 10.0,
        "default_max": 38.0,
        "optimal_min": 20.0,
        "optimal_max": 28.0,
    },
    "humidity": {
        "canonical_name": "humidity",
        "label": "Relative Humidity",
        "unit": "%",
        "physical_min": 0.0,
        "physical_max": 100.0,
        "default_min": 30.0,
        "default_max": 95.0,
        "optimal_min": 55.0,
        "optimal_max": 75.0,
    },
    "solar_radiation": {
        "canonical_name": "solar_radiation",
        "label": "Solar Radiation",
        "unit": "W/m²",
        "physical_min": 0.0,
        "physical_max": 1500.0,
        "default_min": 100.0,
        "default_max": 950.0,
        "optimal_min": 350.0,
        "optimal_max": 650.0,
    },
    "rainfall": {
        "canonical_name": "rainfall",
        "label": "Rainfall",
        "unit": "mm",
        "physical_min": 0.0,
        "physical_max": 500.0,
        "default_min": 0.0,
        "default_max": 50.0,
        "optimal_min": 0.0,
        "optimal_max": 20.0,
    },
    "water_level": {
        "canonical_name": "water_level",
        "label": "Reservoir Water Level",
        "unit": "%",
        "physical_min": 0.0,
        "physical_max": 100.0,
        "default_min": 20.0,
        "default_max": 100.0,
        "optimal_min": 40.0,
        "optimal_max": 90.0,
    },
    "soil_ph": {
        "canonical_name": "soil_ph",
        "label": "Soil pH",
        "unit": "pH",
        "physical_min": 0.0,
        "physical_max": 14.0,
        "default_min": 5.0,
        "default_max": 8.5,
        "optimal_min": 6.0,
        "optimal_max": 7.0,
    },
    "soil_ec": {
        "canonical_name": "soil_ec",
        "label": "Soil Electrical Conductivity",
        "unit": "dS/m",
        "physical_min": 0.0,
        "physical_max": 15.0,
        "default_min": 0.5,
        "default_max": 3.5,
        "optimal_min": 1.2,
        "optimal_max": 2.2,
    },
    "nitrogen": {
        "canonical_name": "nitrogen",
        "label": "Available Nitrogen",
        "unit": "mg/kg",
        "physical_min": 0.0,
        "physical_max": 250.0,
        "default_min": 15.0,
        "default_max": 90.0,
        "optimal_min": 35.0,
        "optimal_max": 60.0,
    },
}


def canonicalize_sensor_type(raw_type: str) -> str:
    cleaned = raw_type.strip().lower().replace("-", "_").replace(" ", "_")
    return SENSOR_CANONICAL_NAMES.get(cleaned, cleaned)


def get_sensor_properties(sensor_type: str) -> Dict[str, Any]:
    canon = canonicalize_sensor_type(sensor_type)
    return DEFAULT_SENSOR_PROPERTIES.get(
        canon,
        {
            "canonical_name": canon,
            "label": canon.replace("_", " ").title(),
            "unit": "",
            "physical_min": 0.0,
            "physical_max": 1000.0,
            "default_min": 0.0,
            "default_max": 100.0,
            "optimal_min": 40.0,
            "optimal_max": 70.0,
        },
    )
